included:
  - Sources
  - Tests
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - let_var_whitespace
  - force_cast
  - anyobject_protocol
  - discouraged_optional_collection
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - inert_defer
  - no_grouping_extension
  - no_magic_numbers
  - required_deinit
  - unused_capture_list
  - file_name

attributes:
  always_on_line_above:
    - "@ConfigurationElement"
    - "@OptionGroup"
    - "@RuleConfigurationDescriptionBuilder"
identifier_name:
  excluded:
    - id
large_tuple: 3
number_separator:
  minimum_length: 5

balanced_xctest_lifecycle: &unit_test_configuration
  test_parent_classes:
    - SwiftLintTestCase
    - XCTestCase
empty_xctest_method: *unit_test_configuration
single_test_class: *unit_test_configuration

function_body_length: 100
type_body_length: 400

custom_rules:
  fatal_error:
    name: Fatal Error
    message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
    regex: \bfatalError\b
    match_kinds:
      - identifier
    severity: error
